# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73f3b45a4511cf4b70e953cb474992060256e16d57e60c75f58469df243c603e21242c7886fd09f5664dcc1e572930b73e417f65b4dcae5012a93ac774351a48
  facebook_app_id: <%= ENV["HOTDOGS_FACEBOOK_USERNAME"] %>
  facebook_app_secret: <%= ENV["HOTDOGS_FACEBOOK_PASSWORD"] %>
  hotdog_app_id: <%= ENV["HOTDOGS_AWS_ACCESS_KEY_ID"] %>
  hotdog_app_secret: <%= ENV["HOTDOGS_AWS_SECRET_ACCESS_KEY"] %>
  hotdog_app_id: <%= ENV["HOTDOGS_AWS_ACCESS_KEY_ID"] %>
  hotdog_app_secret: <%= ENV["HOTDOGS_AWS_SECRET_ACCESS_KEY"] %>


test:
  secret_key_base: ec8df37224028ffe3e14d9637322b70eb69912e5f0ec3475cfa5f16e2b1139658d130efa2babe06f8c46572de229cb7251a7bf797f3ed80059165c9974522e27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
